# Generated by Django 5.0.2 on 2024-03-02 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='origination',
        ),
        migrations.AddField(
            model_name='person',
            name='age',
            field=models.IntegerField(default=21),
        ),
        migrations.AddField(
            model_name='person',
            name='email_address',
            field=models.CharField(default='@princeton.edu', max_length=64),
        ),
        migrations.AddField(
            model_name='person',
            name='last_name',
            field=models.CharField(default='Smith', max_length=64),
        ),
        migrations.AddField(
            model_name='person',
            name='origination_city',
            field=models.CharField(default='Princeton', max_length=64),
        ),
        migrations.AddField(
            model_name='person',
            name='origination_state',
            field=models.CharField(default='NJ', max_length=2),
        ),
        migrations.AddField(
            model_name='person',
            name='vehicle_type',
            field=models.CharField(default='Tesla', max_length=64),
        ),
    ]
